name: Build, Test and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Build
        run: go build -v -gcflags="-m" ./...

      - name: Test
        run: go test -v ./...
  
  Benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go_version:
          - "stable"
          - "oldstable"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go_version }}-${{ hashFiles('.github/workflows/go.yml') }}${{ hashFiles('**/go.sum') }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go_version }}'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Set up Rust
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Oha
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo install --force oha

      - name: Run Benchmark
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
        run: |
          go run ./tests > benchmark.md

      - uses: actions/upload-artifact@v2
        with:
          name: benchmark_pprof_output_${{ runner.os }}-go${{ matrix.go_version }}
          path: testOutput

      - id: make-benchmark-report
        run: |
          go run ./tests/urlescape benchmark.md

      - name: commit-comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.make-benchmark-report.outputs.body }}
